### ISSUE TITLE
Additional SwipeEventCallback methods

### ISSUE THREAD

**Issue by kiezkicker** [aaronbond/Swipe-Deck#10]
Is it possible to to expand the SwipeEventCallbacks with two more callback methods to detect 
1. the top-card is touched and being moved
2. the top-card is not longer touched

Those callbacks would help to find out if e.g. a viewpager should intercept touch events or not.

Thanks for your great work!

**Comment by aaronbond** [comment]
sure thing,
try the latest version (0.2.9) give it a test and let me know how you do.

**Comment by kiezkicker** [comment]
Thanks a lot - this is very helpful
