### ISSUE TITLE
Add the card back

### ISSUE THREAD

**Issue by ZainabMohd** [aaronbond/Swipe-Deck#11]
How can I add the swiped card to the back of the card stack ??

**Comment by aaronbond** [comment]
the best way at the moment would be to do it in the cardsDepleted() callback

once the deck is done you can re add all the cards you want to it and start again. i might make a nicer way to cycle through the cards but at the moment it's up to you to handle it.

**Comment by ZainabMohd** [comment]
I tried to do so but I couldn't get to run cardsDepleted() method?

**Comment by aaronbond** [comment]
ah i see, i broke the cardsdepleted callback with an animation fix. i'll upload a new version

**Comment by aaronbond** [comment]
try updating your version to 0.2.10

**Comment by ZainabMohd** [comment]
I get Gradle sync "Error:Failed to resolve: frankiesardo:icepick:3.1.0"

**Comment by aaronbond** [comment]
what version were you using previously?

**Comment by ZainabMohd** [comment]
0.2.7

**Comment by aaronbond** [comment]
ah ok.

try updating to 0.2.11
seems i forgot to add the repository to icepick and android studio didn't tell me (must have pulled that package from cache, which is strange behaviour i would think)

try that and let me know if it works for you, if that fails for some reason

```groovy
repositories {
  maven {url "https://clojars.org/repo/"}
}
```

add that to your gradle file, either way let me know.

**Comment by ZainabMohd** [comment]
I've updated to the latest version 0.2.11 I got this error:
` Error:A problem occurred configuring project ':app'.
                > Could not resolve all dependencies for configuration ':app:_productionDebugCompile'.
                > Could not find frankiesardo:icepick:3.1.0.
                Searched in the following locations:
        https://jcenter.bintray.com/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
        https://jcenter.bintray.com/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar
        https://repo1.maven.org/maven2/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
        https://repo1.maven.org/maven2/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar
        https://oss.sonatype.org/content/repositories/snapshots/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
        https://oss.sonatype.org/content/repositories/snapshots/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar
        https://maven.fabric.io/public/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
        https://maven.fabric.io/public/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar`

I tried maven and it did the trick. Update the readme file, I thought 0.2.7 is the latest .

Thank you very much for the quick response and for your great work on the library.

It would also be awesome, if you can add this animation to the cards stack. I think a pic will explain better. Sorry I uploaded it zipped because of uploading issue.

Thanks again

[cardstack.zip](https://github.com/aaronbond/Swipe-Deck/files/132128/cardstack.zip)

**Comment by aaronbond** [comment]
yeah sure that's probably doable. adding more robust animations is certainly on my todo list unfortunately i have other things to do and at the moment i'm the only one working on this library. it honestly needs a clean and refactor because it's a bit messy i cranked it out one weekend and have been patching in features ever since.

 i often don't update the readme because i like to test things out for a few versions before i update the readme.
