### ISSUE TITLE
minSdkVersion 11

### ISSUE THREAD

**Issue by kpurushottam** [aaronbond/Swipe-Deck#13]
Hi,
 library is working fine, but not checked yet for lower version 11, will it work same without any problem.

 email : krp.pandit@gmail.com

**Comment by aaronbond** [comment]
I'm not sure what you're asking, It should support all the way back to sdk 12.

I did an experimental branch that will support sdk's less than this but it was more of an exercise to see what it would take it is in a semi functional state and is many revisions out of date.

**Comment by kpurushottam** [comment]
I am using SwipeLinearLayout, with weights assigned to childs, but the swipe-deck does not swipes above all, childs at bottom orientation are still visible on above

**Comment by aaronbond** [comment]
which version of swipe deck are you using?

**Comment by kpurushottam** [comment]
0.2.9

**Comment by aaronbond** [comment]
could you show me an image of what you mean and post your xml layout file please?

**Comment by kpurushottam** [comment]
I have mailed you at : aaron.r.bond@gmail.com
