### ISSUE TITLE
Could not find frankiesardo:icepick:3.1.0.

### ISSUE THREAD

**Issue by navyapramesan** [aaronbond/Swipe-Deck#16]
Please let me know how to solve the following issue. The frankiesardo:icepick is not found.

Error:A problem occurred configuring project ':Trial'.
> Could not resolve all dependencies for configuration ':Trial:_debugCompile'.
   > Could not find frankiesardo:icepick:3.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
         https://jcenter.bintray.com/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar
         file:/home/navya/Documents/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
         file:/home/navya/Documents/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar
         file:/home/navya/Documents/adt-bundle-linux-x86_64-20140702/sdk/extras/google/m2repository/frankiesardo/icepick/3.1.0/icepick-3.1.0.pom
         file:/home/navya/Documents/adt-bundle-linux-x86_64-20140702/sdk/extras/google/m2repository/frankiesardo/icepick/3.1.0/icepick-3.1.0.jar
     Required by:
         Trial:Trial:unspecified > com.daprlabs.aaron:Swipe-Deck:0.2.9

**Comment by aaronbond** [comment]
i've added icepick as a dependency

it's in the readme but make sure you have

```groovy
repositories {
  maven {url "https://clojars.org/repo/"}
}
```

in your gradle file

**Comment by navyapramesan** [comment]
Hey ,
I have added that as well, the thing is I have appcombat v7 in my project so I had to put the Swipe deck as a module in my project to make the dependencies to one app combat. And I have added the icepick as the dependencies in Swipe Deck. Please refer the code attached 
![screenshot from 2016-02-29 18 28 11](https://cloud.githubusercontent.com/assets/5005951/13395050/425287d8-df12-11e5-87a9-b148eeaf007e.png)

**Comment by aaronbond** [comment]
well i see that you're compiling version 3.2.0 which must be a very recent release, and it's looking for version 3.1.0

other than that... not sure.

**Comment by navyapramesan** [comment]
Thanks, but I am still stuck with :AviarySDK:transformResourcesWithMergeJavaResForDebug FAILED :(

**Comment by navyapramesan** [comment]
Thanks for your reply.

**Comment by aaronbond** [comment]
no problems, all the best finding a solution to your problems. happy coding.

**Comment by Duna** [comment]
```
repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://clojars.org/repo/'}
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':library')
    compile 'com.android.support:multidex:1.0.1'
    compile "frankiesardo:icepick:3.1.0"
    provided "frankiesardo:icepick-processor:3.1.0"
}
```
Ant got the error: Error:Could not find frankiesardo:icepick:3.1.0.
Required by:
ElephantMobile:app:unspecified

**Comment by aaronbond** [comment]
could you move over to swipedeck2? i don't believe i use that library.
