### ISSUE TITLE
AviarySDK:transformResourcesWithMergeJavaResForRelease

### ISSUE THREAD

**Issue by navyapramesan** [aaronbond/Swipe-Deck#17]
Hey ,

I am stuck with another issue today :(

FAILURE: Build failed with an exception.
Please find the issue :
* What went wrong:
Execution failed for task ':AviarySDK:transformResourcesWithMergeJavaResForRelease'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE.txt
  	File1: /home/navya/Documents/Workspace/Trial-set/Trial/AviarySDK/libs/commons-lang3-3.3.2.jar
  	File2: /home/navya/Documents/Workspace/Trial-set/Trial/AviarySDK/libs/commons-io-2.4.jar

Do you use any of these jars in Swipe Deck?

**Comment by aaronbond** [comment]
pretty common problem when working with android. what's happening is that there are two files with the same path and name, this is not allowed. 

see an answer from stackoverflow here:

http://stackoverflow.com/questions/27977396/android-studio-duplicate-files-copied-in-apk-meta-inf-dependencies-when-compile

**Comment by navyapramesan** [comment]
Yes and I have already tried adding the following in the gradle file : 

```
packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
```

**Comment by aaronbond** [comment]
and you still get that issue?

**Comment by navyapramesan** [comment]
Unfortunately yes ! :(

**Comment by aaronbond** [comment]
hmm it looks like your problem is with the aviary SDK or some way you've configured it... is it possible you've included it twice? it doesn't seem to be related to swipe deck, perhaps you should ask the aviary guys?

**Comment by navyapramesan** [comment]
It is an ongoing project since 2 years, and I have the aviary since a year now. Did not have any issues with Aviary so far. So I thought may be some files are duplicated from SwipeDeck. :(

**Comment by aaronbond** [comment]
that's strange, it's very hard to diagnose your problem from here. 

there's a couple of things to try though, update aviary to the latest version and remove unneeded libraries from your project. also it seems strange that you would still get those problems when you're telling gradle to ignore those files, are you sure you've edited the correct gradle file? 

if all else fails the only thing that comes to mind is just opening those libraries up in an archive manager and removing those license files. maybe it's a gradle bug? i'm not sure i'm just making total guesses.

**Comment by aaronbond** [comment]
have you noticed that those two library files come from two totally different home directories?

 /home/navya/ and /home/ileaf/

that may be correct but it strikes me as odd

**Comment by navyapramesan** [comment]
Mmm, I understand, its a very little information to sort of the issue.  will try removing those licences and will let you know!

**Comment by aaronbond** [comment]
perhaps you're pointing to two totally different versions of the same library?

**Comment by navyapramesan** [comment]
Nah, that was my mistake !! my apologies, its the same folder. :)

**Comment by navyapramesan** [comment]
Edited the folder reference :)

**Comment by aaronbond** [comment]
http://stackoverflow.com/questions/28261118/android-studio-error-when-adding-adobe-creative-sdk

it seems a few people have been getting your issue if google is any guide, It might be swipe deck but i'm not seeing any references to swipe deck, also i believe i don't include any of those files for this very reason, it should be a fairly clean android library that shouldn't conflict with anything. although i'm only human :)

**Comment by navyapramesan** [comment]
Mmm, let me check what can be done. Thank you for your time :+1: I really appreciate it :)
