### ISSUE TITLE
Duplicate cards

### ISSUE THREAD

**Issue by arvydaszenitech** [aaronbond/Swipe-Deck#18]
Hi,
i have noticed the that swipe deck duplicates cards when app loses focus (turn off the screen or leave app and come back again). Then i swipe 3 cards, after that i i see the same 3 cards to swipe again.

Current behaviour: 

card was swiped right, position in adapter:  -3
card was swiped right, position in adapter:  -2
card was swiped right, position in adapter:  -1
 card was swiped right, position in adapter:  0
 card was swiped right, position in adapter:  1
card was swiped right, position in adapter:   2
 card was swiped right, position in adapter:  3
card was swiped right, position in adapter:   4
....

Desired behaviour: 
 card was swiped right, position in adapter:  0
 card was swiped right, position in adapter:  1
card was swiped right, position in adapter:   2
 card was swiped right, position in adapter:  3
card was swiped right, position in adapter:   4
....

**Comment by aaronbond** [comment]
thanks for the report. let me look into it.

**Comment by aaronbond** [comment]
can i just ask which version you're using?

**Comment by arvydaszenitech** [comment]
0.2.11

**Comment by aaronbond** [comment]
ok i've updated the version to 0.2.12

a small bit of code i'd forgotten to comment out was causing the issue. it should be ok now. let me know.

**Comment by arvydaszenitech** [comment]
now it works with 0.2.12. Thanks ;)

**Comment by aaronbond** [comment]
hopefully no regressions. let me know if anything else goes wrong.

**Comment by arvydaszenitech** [comment]
No i have an other problem - i don't see swipe deck when navigating in tabs. 
My app has 3 tabs, with swipe deck on first tab. I navigate to tab 3 (a this point tab 1 is destroyed). I navigate back to tab 1 (tab 1 recreated with swipe deck), but swipe deck does not appear.

Just to be sure I downgraded to v0.2.11 and it worked correctly with version 11

**Comment by aaronbond** [comment]
hmmm yeah i was afraid there might be a regression somewhere, i'll look into it and come up with a better solution.

**Comment by aaronbond** [comment]
ok try 0.2.13

turns out android works in strange ways i didn't expect. which is pretty usual for android.

**Comment by aaronbond** [comment]
please test it and get back to me.

**Comment by arvydaszenitech** [comment]
swipe deck still doesn't reappear when swiped back to tab 1

**Comment by aaronbond** [comment]
my bad, this is very difficult to do remotely, i'll try again. 

try 0.2.14

**Comment by arvydaszenitech** [comment]
no worries brother ;) i'm amazed how fast you respond to issues! Very cool!
0.2.14 didn't worked as well. Is there any way i could help to debug it?

**Comment by aaronbond** [comment]
I think it's time to make some changes to the test app so i can test it better and reproduce your problem, at the moment i'm just guessing. i'll get back to you.

however if you did want to help out i think it's just a matter of getting the source code from git and adding it to your project then just running a debugger and see what's going wrong. I could help you once you got that far if you wanted to get your hands dirty.

**Comment by aaronbond** [comment]
i've tested the app again, and i can't recreate your issue unfortunately. so i might need a hand with this.

**Comment by aaronbond** [comment]
everything here appears to be working as expected

**Comment by aaronbond** [comment]
could you try cleaning your project and building again just to be on the safe side? (build -> clean project)

**Comment by aaronbond** [comment]
btw i just realised you should be able to debug swipe deck without adding the code as a module / dependency in your project. silly me

**Comment by arvydaszenitech** [comment]
Ok, i cleaned the project, can start debuging. Where should i look?

**Comment by aaronbond** [comment]
we need to see what's happening in onSaveInstanceState and onRestoreInstanceState and why it's not working for you

**Comment by arvydaszenitech** [comment]
childCountOnInstanceSave = 0. could be the problem?

**Comment by aaronbond** [comment]
i'll have to get back to this tomorrow. but maybe if you poke around you'll find the issue.

**Comment by arvydaszenitech** [comment]
Ok, thanks :)

**Comment by aaronbond** [comment]
i'm having trouble reproducing your exact issue, 

i've really got to look into how android expects view state to be handled as my implementation isn't perfect, i'm not even sure if i'm supposed to handle it or if i should leave it to users of the custom view those kinds of things aren't clear, so i'm going to have to do a bit of reading on the subject and try to implement a best practice canonical solution.

but as to your specific issue, i can't be sure what's happening as i can't seem to break swipe deck in the way you have. could you provide me with some more details about what exactly is going on? some screenshots or xml clippings might be helpful here.

**Comment by arvydaszenitech** [comment]
I'm not sure too if you should save state. In my case i'm not saving state - just reloading the cached data which is fine in my case. So the problem happens when i try to reload data for SwipeDeck and SwipeDeck ties to restore state. 
This the layout i'm using:
```
<com.daprlabs.cardstack.SwipeLinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/contentView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/light_background"
    android:theme="@style/Theme.AppCompat.Light"
    android:weightSum="3"
    android:orientation="vertical">

    <com.daprlabs.cardstack.SwipeDeck
        android:id="@+id/swipe_deck"
        android:layout_weight="2"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:card_spacing="10dp"
        app:max_visible="3"
        android:paddingBottom="16dp"
        android:paddingLeft="12dp"
        android:paddingRight="12dp"
        android:paddingTop="12dp"
        android:layout_marginBottom="6dp"
        app:render_above="true"
        app:rotation_degrees="15" />

    <LinearLayout
        android:layout_weight="1"
        android:layout_width="wrap_content"
        android:layout_height="0dp"
        android:layout_marginTop="8dp"
        android:layout_gravity="center_horizontal"
        android:orientation="horizontal">

        <Button
            android:id="@+id/previous"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/previous" />

        <android.support.design.widget.FloatingActionButton
            android:id="@+id/buzz_btn"
            android:src="@drawable/buzz"
            android:text="@string/buzz" />

        <Button
            android:id="@+id/next"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/next" />
    </LinearLayout>
</com.daprlabs.cardstack.SwipeLinearLayout>
```

For now i solved my issue by forcing not to destroy tab when swiping to tab 3.
```
viewPager.setOffscreenPageLimit(2);
```

**Comment by aaronbond** [comment]
yeah that should work

but if you're not wanting the view to keep any state and just handle it yourself (that actually might be correct) then you should just remove onsaveinstancestate and onrestoreinstancestate
