### ISSUE TITLE
Highlight parts of the card when start swiping.

### ISSUE THREAD

**Issue by jcmsalves** [aaronbond/Swipe-Deck#19]
Hi man,

Thanks for the library. It's great and it fits almost all my requirements. There's one thing I can't do.

I have like 2 relative layouts in the bottom of the card with text and image and I would like to highlight (change color) of each of them depending if I'm swiping left or right. Basically similar to what the library already does with the left/right images overlay.

Is there a way to make this work with layouts or maybe another event that I can listen to, to make this works.

Thanks for the help.

**Comment by aaronbond** [comment]
hmm at one point i was going to expose the x and y values for the card to allow for more customization, i haven't done that yet. 

what do you mean by highlight?

**Comment by jcmsalves** [comment]
By highlighting I mean animate a background in my button layouts inside the card view.

I ended up achieving it by setting image left and right as background drawables on the buttons and now I have the desired effect. 

Another thing that would be nice to have smoother animations was to allow custom duration on the swipe ones as they are hard coded in the library. And interpolators.

And also I've been doing some testing and on the swipe left off screen animation if you put the below code to remove the card and get the new card inside animation.endWithAction it looks way smoother.

**Comment by aaronbond** [comment]
if you want to make some changes, send a pull request i'd be happy to add them.

**Comment by jcmsalves** [comment]
Cool. If I have some time in the weekend I'll send a pull request with the little changes I did

**Comment by aaronbond** [comment]
that would be great, and if i have time i'll consider the custom animations
idea. it's a good one.
