### ISSUE TITLE
Programmatically swipe cards?

### ISSUE THREAD

**Issue by varunrramani** [aaronbond/Swipe-Deck#2]
You have done a great job! 
is it possible to swipe the top card programmatically, the way its possible in tinder, i.e. with on click events of buttons.

**Comment by parthivikky** [comment]
I have used this library for my project. I have an issues with it. It is working fine , when running the app in and  above 5.0 (lollipop). But it is not, below 5.0

The first card is placed at last. I mean card stack is reversed. When swiping the card, the last items only dragged. FYI, I have added screenshot below. Sorry for my poor English.

![screenshot_2016-01-11-13-38-12 1](https://cloud.githubusercontent.com/assets/13612417/12228912/a7ebce46-b867-11e5-8944-d8c561415e5c.png)

**Comment by parthivikky** [comment]
Hi varun,

 I do not know you have done or not. But it is possible

**Comment by aaronbond** [comment]
Good suggestion! It's pretty obvious that this is a necessary feature for a lot of people but because i didn't need it i didn't think to add it.

at the moment i'm working on a more serious issue but after that i will release support for this feature.

**Comment by aaronbond** [comment]
Ok the latest version supports this request. could you test the feature and let me know how it goes? just update gradle to 0.2.1 and call 
```java
cardStack.swipeTopCardLeft(); 
```
or
```java
cardStack.swipeTopCardRight(); 
```
to programatically swipe the cards. 

In the new sample app i have bound it to two buttons on the bottom of the screen if you would like an example.

**Comment by varunrramani** [comment]
Thank you! will test and report

**Comment by varunrramani** [comment]
Its working fine! Thanks again!

**Comment by aaronbond** [comment]
when you're swiping? or when you programatically swipe left or right?

**Comment by varunrramani** [comment]
when programatically swiping

**Comment by parthivikky** [comment]
It is too faster when moving out. so left and right image does not appear.

**Comment by aaronbond** [comment]
left and right images don't show when programatically swiping cards, they do swipe rather quickly and so showing them wasn't really necessary as the user wouldn't see them anyway.

what exactly are you asking for?

**Comment by varunrramani** [comment]
Yeah well I tweaked it a little bit to take a bit longer to swipe programmatically, so it is noticeable. I also noticed one more thing just now, when swiping cards programmatically, the cards halt for some time maybe 50 ms before moving out of the screen, may be this is only on the emulator, need to check on device.

**Comment by aaronbond** [comment]
i put in the ability to set the animation duration when programatically swiping cards anyway. it will roll into the next release whenever that might be.

the current version in the git has it though.

**Comment by rajeevjaiswal** [comment]
@aaronbond  @varunrramani Could you please tell how you tweaked to show  image when swiping programatically? 
How to get postion of the current card when swiped programatically?
