### ISSUE TITLE
Found crash on setSelection(int position)

### ISSUE THREAD

**Issue by parthagile** [aaronbond/Swipe-Deck#20]
Hello,

- During implementing swipe-deck to my application, I had one seniores where I have to move my card to selected position for that I am using below code 

 swipeDeck.setSelection(position);

It will give me crash like this : 
 java.lang.UnsupportedOperationException: Not supported

**Comment by aaronbond** [comment]
whatever you're trying to do isn't supported.

could you explain what it is you're trying to do? what kind of behaviour are you looking for?

**Comment by parthagile** [comment]
yes, I had remove one card from deck. Now, I need it back so I call .setSelection(position) that will give me above error.

**Comment by aaronbond** [comment]
perhaps what you want to do is change the adapter ?

**Comment by parthagile** [comment]
No, 

Please take look this code. in cardSwipedRight
swipeDeck.setEventCallback(new SwipeDeck.SwipeEventCallback() {
            @Override
            public void cardSwipedLeft(int position) {
                Log.i(TAG, "card was swiped left, position in adapter: " + position);
                setData(position + 1);
            }
            @Override
            public void cardSwipedRight(final int position) {
                Log.i(TAG, "card was swiped right, position in adapter: " + position);
				
				b = userLogin();
				if(b)
                 swipeDeck.setSelection(position);

                setData(position + 1);
            }

            @Override
            public void cardsDepleted() {
                Log.i(TAG, "no more cards");
            }

            @Override
            public void cardActionDown() {
                Log.i(TAG, "cardActionDown");
            }

            @Override
            public void cardActionUp() {
                Log.i(TAG, "cardActionUp");
            }
        });

**Comment by parthagile** [comment]
I need reopen card.

**Comment by aaronbond** [comment]
try 0.3.1

i've implemented setSelection(int)

**Comment by parthagile** [comment]
Thank you. Now it's working fine. :)

**Comment by aaronbond** [comment]
no worries.
