### ISSUE TITLE
Crash when opening a new activity on clicking a card and returning back. 

### ISSUE THREAD

**Issue by tusharme** [aaronbond/Swipe-Deck#21]
Hi Aaron.

Thanks for providing this great library. I am currently facing an issue.
When I click on a card, I launch another activity.
But when I press back button and then swipe the card, it crashes. 
The crash is because the callback of OnSwipeLeft/Right returns a negative position value and I need to access the data in the array at that position. 
Also the array size increases. 

Is there a way to make it work.
Thanks for the help.

**Comment by aaronbond** [comment]
i'm not sure which version you're on at the moment but try updating to version 0.3.0

note that i've removed state persistence, as far as i can tell that should be up to the user. there were some position problems in an earlier version, let me know if they were fixed.

**Comment by aaronbond** [comment]
I'm going to close this issue as i've heard nothing back on it in a week.
