### ISSUE TITLE
How to change the card's elevation?

### ISSUE THREAD

**Issue by njt28** [aaronbond/Swipe-Deck#22]
Hi Aaron,

Thanks for your great library.
I'm wondering how to change the card's elevation? 
I tried with:

<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    card_view:cardCornerRadius="5dp"
    card_view:cardElevation="2dp"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >
</android.support.v7.widget.CardView>

but nothing changed. Could you please help?

Thanks

**Comment by aaronbond** [comment]
I'm not all that sure what effect you are trying to acheive, card elevation only determines the size of the shadow that is cast by the card and in my testing it works as i expect (it's not actually a part of swipe deck but rather a part of androids card library)

note that 2dp is a small value and casts a rather smallish shadow, although it's more than enough to give the effect of depth.

**Comment by njt28** [comment]
Thanks for your reply,

I'm setting up a deck with 3 cards. I noticed that the shadow of the top and middle card are always bigger than the bottom card. 
I changed the card_view:cardElevation="2dp" but only the bottom card has been affected.
Please, see my screenshots for details:
The bottom card:
http://www.screencast.com/t/t29gUzsQtF5Q

The whole deck:
http://www.screencast.com/t/H3KnUsa42r

Thanks in advance

**Comment by aaronbond** [comment]
Ok a few points,

* the shadows have nothing to do with swipe deck, they're completely out of my purview and control. they are completely a part of CardView which is something you can use with swipedeck (like i do in the example) but you don't have to you can use any view you like and add a drop shadow yourself or have no shadow at all

* I don't see anything wrong in the images you posted, just shadows behaving the way i assume they should
