### ISSUE TITLE
Padding issues on smaller screens

### ISSUE THREAD

**Issue by jcmsalves** [aaronbond/Swipe-Deck#23]
Hey man,

I'm having some issues with this on smaller screens and I think it's because of the padding issue. Why can not I use wrap_content in the swipeframelayout and swipedeck?

If I set this the cards automatically takes full screen and then i have to set padding to make them fit in the right place. This obviously does not work the same way in every screen.

Do you know a way to fix this?

**Comment by aaronbond** [comment]
you'd have to show me some images / xml of your issue, with just this I can't really guess at what might be going on
