### ISSUE TITLE
Recyclerview container with recyclerview adapter

### ISSUE THREAD

**Issue by rajeevjaiswal** [aaronbond/Swipe-Deck#24]
I have implemented your example and I must say the library is good thanks for the library.
Is it possible to use recyclerview adapter instead of base adapter?
I am making an app similar to tinder in terms of functionality so need to know base adapter will be sufficient?

**Comment by aaronbond** [comment]
BaseAdapter should be sufficient. I'm just guessing but i believe recyclerview adapter probably just adds some view recycling stuff.

is that your question?
