### ISSUE TITLE
programmatically and gesture swipe up support

### ISSUE THREAD

**Issue by rajeevjaiswal** [aaronbond/Swipe-Deck#25]
Just like Tinder gives swipe up feature for super like . Is it possible to have another method just like swipe left and swipe right?
I still don't understand the use of 
  cardActionDown() ,   cardActionUp() methods.

Also while swipe left or right programmatically the transition is very fast how can I delay the transition and show the Like Dislike Image?

**Comment by aaronbond** [comment]
mmm i have to confess i haven't had a look at tinder in a long time, there are some things on my todo list for making this library better for a wider range of uses and that is one of them.

it should be pretty easy to add, I can roll out a quick beta version of the feature for you tomorrow if you'd like

of course if that's not quick enough it would not be too much work to add it yourself just adding a method to detect if the card has been swiped up to checkCardForEvent() in SwipeListener and piping the callback through to the user.

**Comment by rajeevjaiswal** [comment]
I will try but it will be great if you could add this functionality

**Comment by rajeevjaiswal** [comment]
I did implement the swipe up functionality but messed up with the animation  So It will be better if you can add 
Below are the imortant codes added 

public void checkCardForEvent() {

        if (cardBeyondLeftBorder()) {
            animateOffScreenLeft(160)
                    .setListener(new Animator.AnimatorListener() {

                        @Override
                        public void onAnimationStart(Animator animation) {

                        }

                        @Override
                        public void onAnimationEnd(Animator animation) {

                            callback.cardOffScreen();
                        }

                        @Override
                        public void onAnimationCancel(Animator animation) {

                        }

                        @Override
                        public void onAnimationRepeat(Animator animation) {
                        }
                    });
            callback.cardSwipedLeft();
            this.deactivated = true;
        } else if (cardBeyondRightBorder()) {
            animateOffScreenRight(160)
                    .setListener(new Animator.AnimatorListener() {

                        @Override
                        public void onAnimationStart(Animator animation) {

                        }

                        @Override
                        public void onAnimationEnd(Animator animation) {
                            callback.cardOffScreen();
                        }

                        @Override
                        public void onAnimationCancel(Animator animation) {

                        }

                        @Override
                        public void onAnimationRepeat(Animator animation) {

                        }
                    });
            callback.cardSwipedRight();
            this.deactivated = true;
        }
            else if (cardBeyondUpBorder()) {
            animateOffScreenUp(160)
                    .setListener(new Animator.AnimatorListener() {

                        @Override
                        public void onAnimationStart(Animator animation) {

                        }

                        @Override
                        public void onAnimationEnd(Animator animation) {
                            callback.cardOffScreen();
                        }

                        @Override
                        public void onAnimationCancel(Animator animation) {

                        }

                        @Override
                        public void onAnimationRepeat(Animator animation) {

                        }
                    });
            callback.cardSwipedUp();
            this.deactivated = true;
        } else {
            resetCardPosition();
        }
    }

    private boolean cardBeyondLeftBorder() {
        Log.d("values2", ""+card.getX()+"---"+card.getHeight()+"---"+parentHeight);

        //check if cards middle is beyond the left quarter of the screen
        return (card.getX() + (card.getWidth() / 2) < (parentWidth / 4.f));
    }

    private boolean cardBeyondRightBorder() {
        //check if card middle is beyond the right quarter of the screen
        Log.d("values1", ""+card.getX()+"---"+card.getWidth()+"---"+parentWidth);

        return (card.getX() + (card.getWidth() / 2) > ((parentWidth / 4.f) * 3));
    }


    private boolean cardBeyondUpBorder() {

        //check if card middle is beyond the Top quarter of the screen
        Log.d("values", ""+card.getX()+"---"+card.getHeight()+"---"+parentHeight);
        return (card.getY() + (card.getHeight() / 2) < ((parentHeight / 4.f )));

    }
    private ViewPropertyAnimator resetCardPosition() {
        if(rightView!=null)rightView.setAlpha(0);
        if(leftView!=null)leftView.setAlpha(0);
        return card.animate()
                .setDuration(200)
                .setInterpolator(new OvershootInterpolator(1.5f))
                .x(initialX)
                .y(initialY)
                .rotation(0);
    }

    public ViewPropertyAnimator animateOffScreenLeft(int duration) {
        return card.animate()
                .setDuration(duration)
                .x(-(parentWidth))
                .y(0)
                .rotation(-30);
    }


    public ViewPropertyAnimator animateOffScreenRight(int duration) {
        return card.animate()
                .setDuration(duration)
                .x(parentWidth * 2)
                .y(0)
                .rotation(30);
    }

 public ViewPropertyAnimator animateOffScreenUp(int duration) {
        return card.animate()
                .setDuration(duration)
                .x(0)
                .y(-(parentHeight))
                .rotation(0);
    }

I dont know much about animations so looking up to your code I just assumed and wrote the values

cardBeyondUpBorder() and animateOffScreenUp is important because swipe up works properly but doing it programmatically it doesnot work for first two child and starts working from 3rd position

**Comment by rajeevjaiswal** [comment]
https://github.com/rajeevjaiswal/Swipe-Deck.git You can check here

**Comment by rajeevjaiswal** [comment]
@aaronbond any update?

**Comment by aaronbond** [comment]
sorry i've been busy this past week, but it's still on my todo.

**Comment by rajeevjaiswal** [comment]
@aaronbond It will be great if features like swipe up, swipe down, re add previous card can be optional in the library

**Comment by rajeevjaiswal** [comment]
@aaronbond I really need this feature are you going to work on it? please let me know

**Comment by aaronbond** [comment]
Hey rajeev,

sorry about the delay I've been extremely busy with other commitments lately

in addition I've put off small changes to completely re write the code base
and improve the overall quality.

let me see if i can whip something up though

**Comment by rajeevjaiswal** [comment]
Hi @aaronbond ,

Any updates regarding this?

**Comment by aaronbond** [comment]
Hi, unfortunately i have had a lot more work and extra curricular activities than i anticipated lately and no time to add these featurese myself (or work on the re write) i have a big hackathon this weekend but i should be able to get it done after that as my responsibilities cool down a little then. 

sorry about that, but if you really want it it's not difficult to do and you can send me a pull request with the feature.

**Comment by rajeevjaiswal** [comment]
@aaronbond If you see above I have tried to implement the swipe up feature and it works but swipe up programatically animation misbehaves for the first two data in the array list.
I shall wait till your hackathon get over.
Goodluck for your hackathon.

**Comment by imaNNeoFighT** [comment]
hi,
i need this feature too  :(

**Comment by aaronbond** [comment]
https://github.com/aaronbond/SwipeDeck2 << please try this version and if it is missing any feature raise a new issue there and i will add it very promptly.
