### ISSUE TITLE
Undo Option on Card-Deck

### ISSUE THREAD

**Issue by nomanbiniqbal** [aaronbond/Swipe-Deck#26]
This is only my request can you please add some function to add Undo support .
It will be like when i click on undo it will swap back last card which i have been swapped

**Comment by anashmamouch** [comment]
yes please i'm looking for the same functionality too.

**Comment by aaronbond** [comment]
alright when i find some time i'll add it in.

**Comment by nomanbiniqbal** [comment]
Hmm any feedback.. :)

**Comment by O-liverQueen** [comment]
please add this functionality, I am very much in need of this..... PLZ

**Comment by ahmetcj4** [comment]
@aaronbond is there any improvement in adding this functionality?

**Comment by erolkaftanoglu** [comment]
we need to know large informations about undo futures.

**Comment by aaronbond** [comment]
https://github.com/aaronbond/SwipeDeck2 << please try this version and if you need a new feature, add an issue and i'll add it very quickly.
