### ISSUE TITLE
Swiping Quickly Freezes Deck

### ISSUE THREAD

**Issue by shaunkutch** [aaronbond/Swipe-Deck#29]
This issue looks like it could be related to issue #7 

I mainly see this while swiping cards to the left. If you swipe a second card quickly and it's swipe animation completes just before the first RemoveViewOnAnimCompleted AsyncTask completes. The third card fails to be setup causing there to be no registered touch events. The second card is then not removed and can be seen just off screen to the left. You have to swipe very quickly. It does not happen when calling the swipeTopCardLeft method programmatically.

I feel this may be related to issue #7 as I am also seeing the slight pause before the card is removed. I assume this is due to the AsyncTask. This short pause seems to be the window in which the issue will occur.

**Comment by shaunkutch** [comment]
Here is a quick video reproducing the issue. https://youtu.be/ZQcxLjS9yK0

**Comment by aaronbond** [comment]
i'm going to re work the current version and change it, unfortunately android threw a lot of curve balls my why while i was developing this  forcing me to change quite a lot and program in a bunch of work arounds.

i'll spend a couple of days refactoring and cleaning up the way it works to better fit in with all the android quirks.

**Comment by shaunkutch** [comment]
I agree, I feel the ordering of events could be ironed out a bit. I did however put in a pull request that is a temporary fix at least.

**Comment by umair151** [comment]
I was about to report the same issue. Its freezing on quickly swiping to left side.

**Comment by aaronbond** [comment]
https://github.com/aaronbond/SwipeDeck2 << please move to this version
