### ISSUE TITLE
Issues with below lollipop version

### ISSUE THREAD

**Issue by parthivikky** [aaronbond/Swipe-Deck#3]
I have used this library for my project. I have an issues with it. It is working fine , when running the app in and above 5.0 (lollipop). But it is not, below 5.0

The first card is placed at last. I mean card stack is reversed. When swiping the card, the last items only dragged. FYI, I have added screenshot below. Sorry for my poor English.

![screenshot_2016-01-11-13-38-12](https://cloud.githubusercontent.com/assets/13612417/12229086/be22908a-b869-11e5-8a0d-e0a01af6f556.png)

**Comment by aaronbond** [comment]
Hello, thankyou for reporting this issue.
I'm aware of this and a fix is coming very soon, it's a rather complicated issue requiring me to rethink how Z-axis is handled on older versions of android.

hopefully the solution i'm about to roll out works well and is bug free. i'd estimate a release will be out within a few hours that should fix this issue.

**Comment by parthivikky** [comment]
Thanks for the support Mr. Aaron. 

I am looking forward for this fix. Let me know if you fixed once.

**Comment by aaronbond** [comment]
Try out the latest version please and give me some feedback, it is relatively untested and there has been a lot of changes.

**Comment by parthivikky** [comment]
Ok Sure.. Just wait.

**Comment by parthivikky** [comment]
What i have to do to update your latest version

**Comment by parthivikky** [comment]
Still same problem. I just synchronized the gradle once. i want to do anything except gradle sync.

**Comment by aaronbond** [comment]
did you change the version number in gradle? to 0.2.0 as per the readme?

**Comment by parthivikky** [comment]
Ah.. It is fixed. You are really great. It will test with some other versions and let you know.

**Comment by parthivikky** [comment]
It is working well. Thank you Mr. Aaron. I would like to keep in touch with you. I want to become a good programmer.

**Comment by aaronbond** [comment]
No worries. If you want to become a good programmer asking a lot of questions and using a lot of other peoples code is certainly the way to do it.
