### ISSUE TITLE
Swipe all items

### ISSUE THREAD

**Issue by MinaMohsen** [aaronbond/Swipe-Deck#34]
Can not swipe all cards , always there are 2 cards , i can not swipe them ??

**Comment by aaronbond** [comment]
could you please provide some more information about your issue? which version of swipe deck are you using? and how are you swiping the cards? etc.

**Comment by MinaMohsen** [comment]
Sorry i download it from download zip and use it , but when i use from dependencies it work well , 
Sorry for that and i wish you add swipe up  and rewind card also

**Comment by MinaMohsen** [comment]
and please update your source code because there is something wrong happened when i download the project from download zip button on github

**Comment by MinaMohsen** [comment]
and please add option to show left image and right image when swipe cards using buttons

**Comment by aaronbond** [comment]
yes i haven't done a proper "github release" in a very long time, the best way to get the source code is actually to git clone the repository not download the zip.

**Comment by iqtrix** [comment]
me too facing same issue.. please fix it

**Comment by aaronbond** [comment]
https://github.com/aaronbond/SwipeDeck2 << new version, please try this one.
