### ISSUE TITLE
Select Particular index on click

### ISSUE THREAD

**Issue by pixelbendr** [aaronbond/Swipe-Deck#36]
So I have a list of profiles in an Array List and I want the user to be able to start swiping from anywhere in the list. is there a method for initialising this approach or another event like cardStart or cardEnd?

**Comment by pixelbendr** [comment]
Any info on this?

**Comment by aaronbond** [comment]
Hi, sorry about being away from github for an extended period. 

that would be a difficult feature to add in this version, but if you are still interested in it, please raise an issue on https://github.com/aaronbond/SwipeDeck2 and i'll add it.
