### ISSUE TITLE
Cyclic looping through cards 

### ISSUE THREAD

**Issue by nileshpa** [aaronbond/Swipe-Deck#37]
Hi Aaron , 
First I would like to thank you for this great library. I would like to use it in my project. I was wondering if there is a way to enable cyclic looping through the cards on swipe/up/down, instead of removing it?

**Comment by pixelbendr** [comment]
@nileshpa I think looping is default behaviour.

**Comment by QiXi** [comment]
+ need cyclic looping

**Comment by aaronbond** [comment]
if you still want this feature please raise an issue on https://github.com/aaronbond/SwipeDeck2
