### ISSUE TITLE
Edges of the cards on the top

### ISSUE THREAD

**Issue by playeronee** [aaronbond/Swipe-Deck#39]
Hey,

Thanks for Great solution to fast implement tinder move.
Do you have an idea how to move the edges of the cards on top of the stack? (Image: [http://oi65.tinypic.com/icsmcp.jpg](http://oi65.tinypic.com/icsmcp.jpg)) Default they are on the bottom.

Regards,
Michal

**Comment by playeronee** [comment]
I'm sorry, I hurried up. Just set swipedeck:card_spacing with minus value. Regards.

**Comment by aaronbond** [comment]
no problems, glad you figured it out on your own.

i've moved development to a new version https://github.com/aaronbond/SwipeDeck2.
