### ISSUE TITLE
Cannot swipe the second to last card.

### ISSUE THREAD

**Issue by qteen1** [aaronbond/Swipe-Deck#40]
Hey man, 

First I would like to compliment you on how you strucuted the code really well. But I can't seem to find the issue to your bug. 

I swipe through all the cards fine, but when I get to the second to last card. I cannot swipe it. 

In order for me to swipe the second to last card, I have to press the "add cards" button. To add more cards. Then I can swipe cards again UNTIL (again) I reach the second to last card. 

So no matter what, I cannot swipe the second to last card. How can I fix this error and where in the code is the problem located?

Cheers~

**Comment by pranayairan** [comment]
I am seeing that issue as well, i can not swipe the second last card.

**Comment by njt28** [comment]
Hi guys, @qteen1 @pranayairan 
do you have any solutions?

**Comment by aaronbond** [comment]
please try using https://github.com/aaronbond/SwipeDeck2

**Comment by qteen1** [comment]
Thanks Aaron. I will try this out soon and get back to you with updates!

**Comment by jituiitm** [comment]
final View child = getChildAt(getChildCount() - childOffset);

replace with 

final View child = getChildAt(0);
