### ISSUE TITLE
Add card to top of stack programmatically 

### ISSUE THREAD

**Issue by laylizzlle** [aaronbond/Swipe-Deck#41]
Thanks for this wonderful library.I'm trying to add an item to the top of the stack when a user clicks a button. Tried adding the item at index zero nd call notifyDataSetChanged but didn't work.Any help?

**Comment by aaronbond** [comment]
i haven't implemented a feature like that yet, if you still want it could you add an issue on https://github.com/aaronbond/SwipeDeck2 ?

**Comment by lazar108** [comment]
`final SwipeDeckAdapter adapter = new SwipeDeckAdapter(product, this);
        cardStack.setAdapter(adapter);

Button btn = (Button) findViewById(R.id.button);
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                cardStack.setSelection(desIndex - 1);
            }
        });
`

This is how I ended up doing it.
