### ISSUE TITLE
programatically swiping card and left

### ISSUE THREAD

**Issue by manojkumar123** [aaronbond/Swipe-Deck#44]
am unable to do swipe card right or left programatically. as you have given some methods like cardStack.swipeTopCardRight() its is having some paramter like duration which is not explained in your example. and i want animation  to occur just as when we swipe even though we doi programtically.

**Comment by aaronbond** [comment]
you will have to elaborate, the parameter is the animation duration in milliseconds (it swiped left/right from the center to off screen in that time.)
