### ISSUE TITLE
Last two items are not swiping in demo project

### ISSUE THREAD

**Issue by kimeeo** [aaronbond/Swipe-Deck#45]
Last two items are not swiping in demo project.

**Comment by njt28** [comment]
I also got this problem! 
@kimeeo : any solutions so far?

**Comment by dev01-adroitinfosol** [comment]
I too got the same problem. I am not able to swipe last two items.

**Comment by dev01-adroitinfosol** [comment]
i want video to be played inside each card, i am able to achieve this using TextureView to play the Video. and Fortunately it works well, 
But results in slower performance. There might be a reason of the views not getting recycled.

**Comment by CodeBoyChd** [comment]
You have to customize the implementation in setupTopCard

**Comment by penzrgb** [comment]
@CodeBoyChd could you please elaborate

**Comment by aaronbond** [comment]
please try moving over to SwipeDeck2: https://github.com/aaronbond/SwipeDeck2

it's a little better designed than this version.

**Comment by jituiitm** [comment]
final View child = getChildAt(getChildCount() - childOffset);

replace with 

final View child = getChildAt(0);
