### ISSUE TITLE
I am not able to swipe last two items.

### ISSUE THREAD

**Issue by dev01-adroitinfosol** [aaronbond/Swipe-Deck#47]

**Comment by dev01-adroitinfosol** [comment]
i want video to be played inside each card, i am able to achieve this using TextureView to play the Video. and Fortunately it works well, 
But results in slower performance. There might be a reason of the views not getting recycled.

**Comment by jituiitm** [comment]
final View child = getChildAt(getChildCount() - childOffset);

replace with 

final View child = getChildAt(0);
