### ISSUE TITLE
video in place of imageview

### ISSUE THREAD

**Issue by dev01-adroitinfosol** [aaronbond/Swipe-Deck#48]
i want video to be played inside each card, i am able to achieve this using TextureView to play the Video. and Fortunately it works well, 
But results in slower performance. There might be a reason of the views not getting recycled.

**Comment by aaronbond** [comment]
i don't think it's to do with the views not being recycled. playing videos in a card would be tricky, it would be something i would have to investigate. i'm really not sure how to efficiently move and rotate a video around the screen as of now.
