### ISSUE TITLE
Limit to only swipe left or right, not anywhere around the layout

### ISSUE THREAD

**Issue by aimanbaharum** [aaronbond/Swipe-Deck#49]
Hey, great library, I must say. I was wondering though, is it possible to limit the swiping to only go left or right, but not freely around the layout?

In my case here, I have a page where I put this swipedeck at the top and other views (horizontal recyclerview etc) below it. So, swiping around freely isn't going to look nice as it would cut the swiping cards at the edge of another views. Plus, scrolling the page up and down is disturbed by the free swiping mechanism.

**Comment by iamwire** [comment]
hey @aimanbaharum 

Were you able to resolve this issue? 

@aaronbond @shrewduser I love this lib would be happy to explore how we can get an enhanced version of same

Cordially,

**Comment by aimanbaharum** [comment]
Not yet. I just use the free swiping as of now. I was wondering if there is other lib that can do this instead of using Swipe-Deck, which is obviously specifically for "swiping freely".

**Comment by aaronbond** [comment]
yes... should be doable with an update. if you guys still want this i could add it to the new version 

https://github.com/aaronbond/SwipeDeck2
