### ISSUE TITLE
CardView is not focusable on below 5.0 

### ISSUE THREAD

**Issue by parthivikky** [aaronbond/Swipe-Deck#5]
I want to switch to next screen when click on the card. But In below 5.0, card is not focusable sometimes. So onClickListener is not calling. In 0.1.0 version, cardClicked() method was available in SwipeEventCallback interface. But In latest version, it is not available. So could you please add the method again.

**Comment by aaronbond** [comment]
Yeah i've removed that to allow for a more canonical way of setting on click listener. you now do it in the same way you would on other collection views (which is really the right way to do it i added that method rather naively) please see the updated app code.

```java
    public class SwipeDeckAdapter extends BaseAdapter {

        private List<String> data;
        private Context context;

        public SwipeDeckAdapter(List<String> data, Context context) {
            this.data = data;
            this.context = context;
        }

        @Override
        public int getCount() {
            return data.size();
        }

        @Override
        public Object getItem(int position) {
            return data.get(position);
        }

        @Override
        public long getItemId(int position) {
            return position;
        }

        @Override
        public View getView(final int position, View convertView, ViewGroup parent) {

            View v = convertView;
            if (v == null) {
                LayoutInflater inflater = getLayoutInflater();
                // normally use a viewholder
                v = inflater.inflate(R.layout.test_card2, parent, false);
            }
            //((TextView) v.findViewById(R.id.textView2)).setText(data.get(position));
            ImageView imageView = (ImageView) v.findViewById(R.id.offer_image);
            Picasso.with(context).load(R.drawable.food).fit().centerCrop().into(imageView);

            v.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    String item = (String)getItem(position);
                    Log.i("MainActivity", item);
                }
            });
            return v;
        }
    }
```

as you can see you simply add a click listener in the adapter class you created. simple really and it's much more flexible.

**Comment by aaronbond** [comment]
by the way whenever i break the API i usually change the documentation (README) file so check there for changes.

**Comment by parthivikky** [comment]
I tried the following code. But it is also not working.

v.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    String item = (String)getItem(position);
                    Log.i("MainActivity", item);
                }
            });

**Comment by aaronbond** [comment]
hmm i gave it a test myself, it works, but not as well as it should. what's probably happening is that slight moves in the card when you tap it are stealing away the ontouch event. 

I'll work out a more robust solution.

**Comment by aaronbond** [comment]
Ok i've pushed a new version with better detection of onClicks, let me know how you find it. 

update gradle version to 0.2.2

**Comment by aaronbond** [comment]
oh and btw, i've updated a couple of other things, but it should be fairly obvious how to use everything.
