### ISSUE TITLE
Reusing of the removed view

### ISSUE THREAD

**Issue by CodeBoyChd** [aaronbond/Swipe-Deck#50]
Great Library first of all. I have customized it for some data points. 
I was trying to reuse the view where the TODO has been written..
@aaronbond Have you tried resolving this TODO..
The view get stuck again if used the removedView as convertview..

**Comment by aaronbond** [comment]
with a relatively slow 'scroll speed' ie... you are only every dealing with a half dozen views max at a time (if you're using more maybe we should talk about that) view recycling wasn't really high on the agenda for performance.

it's something to add to swipedeck2 (https://github.com/aaronbond/SwipeDeck2) but i've found performance to be satisfactory even on very old devices.
