### ISSUE TITLE
Using Swipe Deck inside NestedScrollview is creating issues

### ISSUE THREAD

**Issue by falduappoorva** [aaronbond/Swipe-Deck#51]
This library is really helpful, easing up the work to the great extend!!

I found one Issue, When i am using the NestedScrollView as a Parent Layout and pass the fragment of SwipeDeck. It causing problem in animating. 

1) It doesnt smoothy goes off on Left/Right on single swipe. Card Stucks and needs multiple swipe to swipe it off.
2) If it drag to some extend than double clicking will swipe off the Card.
3) I have disable the click of Parent also tired with setting the nestedscrollviewenabled = false. 

Can anyone help me in resolving the Issue. @aaronbond 

Thanks.

**Comment by aaronbond** [comment]
sorry for taking so long to reply, are you still having this issue? could you try the new version at 
https://github.com/aaronbond/SwipeDeck2 ?
