### ISSUE TITLE
Crash on programatically removing all cards on a button click.

### ISSUE THREAD

**Issue by tusharme** [aaronbond/Swipe-Deck#53]
I need to programatically remove all the cards on the click of  a button.
feedList is my dataset array. I am doing the following:

feedList.clear();
adapter.notifyDataSetChanged();/

Behavior: The cards become blank but they still remain on the screen and the app crashes.
Please help. Thanks.

**Comment by aaronbond** [comment]
this should be doable in swipedeck2 i just checked. 

https://github.com/aaronbond/SwipeDeck2

let me know how it works out for you
