### ISSUE TITLE
Allow adding an overlay view

### ISSUE THREAD

**Issue by AdityaAnand1** [aaronbond/Swipe-Deck#56]
Pretty much [this](https://dribbble.com/shots/2219454-Freebie-Principle-Card-Swipe-Template) dribbble.

![shot](https://cloud.githubusercontent.com/assets/13274079/17277116/fb9c912a-5758-11e6-9bed-ea60324bff2a.gif)

[This](https://github.com/wenchaojiang/AndroidSwipeableCardStack#listening-to-card-stack-event-) similar library provides a Viewpager's` transformPage() `kinda callback. I think something like this could accomplish the above gif. Just like a viewpager, as the card is being swiped off, by using the 'swipe distance', we can linearly interpolate an alpha value to apply to an 'overlay view' on top of each card.

I can think of two ways to approach this:
* This library could take in an optional overlay view and do all this automatically. Super convenient for this specific use case (like in the above gif), but not very flexible.
* Provide a 'swipe distance callback' and let us do whatever we want with it (like changing the alpha of the overlay on top of the card ourselves). I've only glanced at the implementation but it looks like we could have a callback out of `onTouch()` in `SwipeListener` that gives access to the top most card's x and y position (normalized).

*Edit: I think the second way might even provide a broader alternative to the right/left indicator images.

Assuming of course, you like the idea. What do you think?

**Comment by aaronbond** [comment]
I'm sorry i haven't responded to this, i've been busy and also re writing this view from the ground up as swipedeck2 (https://github.com/aaronbond/SwipeDeck2)

this effect can already be done though, just have two views covering the whole card and set them as the left and right image and you will get exactly this.
