### ISSUE TITLE
Swipe deck with Cursor adapter notifyDataSetChanged doesn't work perfectly

### ISSUE THREAD

**Issue by JiajunWong** [aaronbond/Swipe-Deck#6]
mSwipeDeck.setAdapter(mCursorAdatper);
...
@Override
public void onLoadFinished(Loader<Cursor> loader, Cursor data){
    mCursorAdatper.swapCursor(data);
}

For the code above. Swipe deck cannot update UI immediately.

**Comment by JiajunWong** [comment]
Please give me some suggestions.

I try to debug. seems like "nextAdapterCard" does not reset when adapter data set changed.

How can I solve this?

Thanks so much.

**Comment by aaronbond** [comment]
mmm, yes your suspicion is probably correct! 

I've been thinking about changing this, it's been on my mental TODO list for a while, basically i made it so you can add things to the adapter but not change it completely. I haven't looked into it but this is probably the wrong way to do it. 

I'll take a look at how adapters are supposed to be handled and implement the correct behaviour.

**Comment by aaronbond** [comment]
Ok go ahead and try the latest version and see if that fixes your issue.

if not then it's something else and i'll have to look into it.

**Comment by JiajunWong** [comment]
Thanks soooo much. Let me try the latest version.

**Comment by JiajunWong** [comment]
Still no luck. 
I think at SwipeDeck.java. 
private void removeTopCard(){
...
//if there are no more children left after top card removal let the callback know
        if (getChildCount() <= 0 && eventCallback != null)
        {
            eventCallback.cardsDepleted();
            nextAdapterCard = 0;
        }
}

should also set nextAdapterCard to 0.

**Comment by aaronbond** [comment]
if you think there's an easy fix, feel free to add it and test it then let me know.
it's very easy to pull the code into your project instead of using the binaries.

```
http://stackoverflow.com/questions/24658422/android-studio-0-8-1-creating-modules-without-copying-files
```
this post has an ok method of including another project as a dependency. for now i'll read what the proper behaviour for an adapter view is and if my implementation breaks that contract i'll change it and get back to you.

**Comment by aaronbond** [comment]
from what i can tell, what i'm doing is the correct behaviour... 

also could you let me know what you mean by your initial post so i can get a better idea of what's not working for you?

what do you mean by "For the code above. Swipe deck cannot update UI immediately."
