### ISSUE TITLE
Card halts when swiping programmatically

### ISSUE THREAD

**Issue by varunrramani** [aaronbond/Swipe-Deck#7]
Hey,

When swiping the card programmatically to left, the card halts for around 500 ms before exiting the screen. I'm using 0.2.1 version.
Tested on Moto e 2nd  gen, genymotion emulator.

Not happening when swiping the cards manually

**Comment by aaronbond** [comment]
I can't reproduce this problem, even on very old hardware.

could you give me more information?

**Comment by varunrramani** [comment]
there was nothing in the logs but i've created a video of it and it happens only on left swipe, right swipe works fine.

https://www.youtube.com/watch?v=K-JGhiCEmAU

also i'm implementing it in a viewpager

**Comment by aaronbond** [comment]
and it only happens when you swipe left? can you show me a video of swiping right?

that little pause before your app generates the next card, does it only happen when swiping left? 

have you tried updating to 0.2.4?

**Comment by aaronbond** [comment]
I'm trying to reproduce this problem in the sample application but i haven't managed to yet. I need a better idea of what might be going wrong here, can you profile / debug your app and figure out where the pause is occurring?

**Comment by varunrramani** [comment]
I updated to latest version and I'm still facing the same issue. video of it is on the following link:

https://www.youtube.com/watch?v=b3dYK-frOb4

**Comment by aaronbond** [comment]
hmmmm i'm not sure about that halt but i feel like i know what's going on with the card not going all the way out of the screen.

it's probably that you've wrapped up the swipe view in something else and the card only swipes to the end of its parent view. as a fix i might sure it always swipes off screen instead of off the parent view and see if that fixes your issue.

**Comment by varunrramani** [comment]
i have the swipedeck inside a normal relative layout.

**Comment by varunrramani** [comment]
following is my fragment xml:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:swipedeck="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.daprlabs.cardstack.SwipeDeck
        android:id="@+id/tinderSwipeDeck"
        android:layout_width="match_parent"
        android:layout_height="400dp"
        android:layout_below="@id/searchRLL"
        android:layout_centerHorizontal="true"
        android:paddingLeft="@dimen/padding_large"
        android:paddingRight="@dimen/padding_large"
        swipedeck:card_spacing="5dp"
        swipedeck:max_visible="3"
        swipedeck:opacity_end="0.2"
        swipedeck:render_above="true"
        swipedeck:rotation_degrees="15" />

    <Button
        android:id="@+id/productLikeButton"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_alignParentRight="true"
        android:layout_below="@id/tinderSwipeDeck"
        android:layout_marginRight="@dimen/margin_xxxxlarge"
        android:background="@drawable/loving4red" />

    <Button
        android:id="@+id/productDislikeButton"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_alignParentLeft="true"
        android:layout_below="@id/tinderSwipeDeck"
        android:layout_marginLeft="@dimen/margin_xxxxlarge"
        android:background="@drawable/broken4red" />


</RelativeLayout>

**Comment by aaronbond** [comment]
I've got a few things to do but i'll be writing something that will hopefully fix your issues soon. i'll post here when i release it.

**Comment by varunrramani** [comment]
@aaronbond okay thanks!

**Comment by aaronbond** [comment]
try version 0.2.5

if that doesn't work i have another fix.

**Comment by aaronbond** [comment]
how'd you go?

**Comment by varunrramani** [comment]
was working on something else for past few day. will test tomorrow first thing in the morning.
