### ISSUE TITLE
CardStack not initializing properly

### ISSUE THREAD

**Issue by thejaswinims** [aaronbond/Swipe-Deck#9]
When you come back from some other activity, though the data passed to adapter is correct, it is not initializing CardStack properly. it shows different item or empty card stack.

How can i get the current visible item from adapter?

**Comment by aaronbond** [comment]
yeah, that's something i haven't gotten around to yet, sure i'll put that in the next update. maybe tomorrow?

for now it is certainly possible to persist the state yourself and restore it when your activity reloads.

**Comment by thejaswinims** [comment]
Am initializing it in onResume() function?

**Comment by thejaswinims** [comment]
Thank you.

**Comment by aaronbond** [comment]
no problem.
